version: "3.3"

services:
  backend:
    container_name: preservetube-backend
    image: ghcr.io/preservetube/backend
    networks:
      - public
    restart: on-failure
    volumes:
      - /mnt/hdd/preservetube-videos:/usr/src/preservetube/backend/videos
      - ./.env:/usr/src/preservetube/backend/.env
      - ./s3.json:/usr/src/preservetube/backend/s3.json

networks:
  public:
    external: true
    name: public