import redis from '@/utils/redis';

const channelBlacklist = [
  'UCR7d_LMsADXorkUF5fkcEHQ',
  'UCgcX8KN9tjesfSg1KYW8JMA',
  'UCRbV62Z7jv5j9WHdjCQT4BQ',
  'UCErCs-HgXDfj_79jbWO8SqA',
  'UClt1wsBuiIJS8_RoAFlkSlQ',
  'UCviJ2KzLw4W7zRNzPv6FLbA',
  'UCUQmW2YLzhEmMTqO0RAPlOw',
  'UCtmnjVU-u1B7vX-XDhuvExA',
  'UCgcX8KN9tjesfSg1KYW8JMA',
  'UCh8VpxMSRm-JoogNpCFHbMw',
  'UCUQmW2YLzhEmMTqO0RAPlOw',
  'UC4Anp9y2TU-d5blFUf7wCqw',
  'UC-TaLb_bURExFdLFXkJ3Adg',
  'UC1XgosSxwK9xtrMLsRzCbHw',
  'UCInXezQxpWgrd7uPKeA6gPQ',
]

async function analyseSlop(id: string, title: string, description: string) {
  const llmResponse = await (await fetch('https://nano-gpt.com/api/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': 'Bearer ' + process.env.NANOGPT_API,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      model: 'deepseek/deepseek-v3.2',
      messages: [
        { role: 'user', content: `You are "The Slop Detector." Analyze video titles and determine if the content is SLOP or NOT SLOP.

### DECISION RULES
**Score SLOP if the video matches either of these categories:**
**1. Slop Edit** — a formulaic fan/character edit. Look for a combination of these signals:
- **Emoji in title** — strong signal, especially 😂🤣😎😍🥺. Multiple emoji = very strong. (optional)
- **Title is entirely hashtags, or mostly hastags** — near-instant slop
- **Hashtag spam** — title consists of a short hook followed by 3+ hashtags, or the description is dominated by hashtags. Strong signal on its own.
- **Unicode styled text** (𝐋𝐢𝐤𝐞 𝐓𝐡𝐢𝐬) — common in character edits (optional)
- **Pipe separators** (|) are only a signal when the segments themselves are slop elements (character name | franchise | song title). Pipes used for general formatting, listing topics, or separating unrelated phrases do not count under any circumstances.
- **4K / [4K] tag** — strong signal when paired with anything else (optional)
- **"Edit" / "OneShot" / "Morphosis"** as suffix or with delimiters (║ Edit ║, 「Edit」)
- **Slowed / Reverb / Slowed+Reverb / MONTAGEM** — only counts when stacked with other signals
- **Known slop franchises** — this list is exhaustive, not illustrative. Only these qualify: Johnny English, Mr. Bean, Breaking Bad, Peaky Blinders, American Psycho, Patrick Bateman, The Boys, Homelander, Dexter, Joe Goldberg, Squid Game, Rick Grimes, Thomas Shelby, John Wick, Kingsman. Must be explicitly named.
- **Song name explicitly in title** — especially if slowed or remixed
- **Description** — hashtag spam or music credits reinforce title signals
- **Title mirrors description exactly** — reinforces slop when combined with other signals (optional)
**2. Raw clip** — an unedited or minimally edited fragment of a TV show or movie with no transformative content.
**3. AI-generated compilation** — footage generated by AI tools. Score SLOP if:
- Title or description explicitly mentions "Sora" or "VEO3" OR
- Title or description explicitly mention that the video is a compilation of AI-made videos

### EXCEPTIONS
Always score NOT SLOP:
- News, commentary, politics
- Lost or archived content

### NOTES
- Emoji alone does not make something slop
- A character reference alone does not make something slop
- Pipes and emoji together are not sufficient for a SLOP ruling without additional corroborating signals
- ASMR, art, cooking, and similar creator content is NOT slop even if it uses emoji or pipes
- Do not infer or assume anything about creators, channels, or franchises not explicitly listed in the known slop franchises. If it's not on the list, it's not a signal.
- A channel with social links, Discord, Patreon, and editor credits in the description is a legitimate creator, not a slop channel

### OUTPUT
Valid JSON only. No other text. One sentence reasoning max, be brief.

{"is_slop": true/false, "reasoning": "..."}

User Title: ${title}
User Description: ${description.slice(0,500)}` }
      ]
    })
  })).json() 

  let parsedResponse: {is_slop: boolean, reasoning: string} 
    = { is_slop: false, reasoning: 'failed to parse' }
  
  try {
    parsedResponse = JSON.parse(llmResponse.choices[0].message.content.replace(/```json|```/g, '').trim())
    console.log(`parsed ${id} - ${JSON.stringify(parsedResponse)}`)
  } catch (e) {
    console.log(`failed to parse ${id} - ${llmResponse.choices[0].message.content}`)
  }

  return parsedResponse
}

async function parseSlop(id: string, title: string, description: string, channelId: string): Promise<boolean> {
  if (channelBlacklist.includes(channelId)) return true;

  const cachedSlop = await redis.get(`slop:${id}`)
  if (cachedSlop) return cachedSlop == 'true' ? true : false

  const { is_slop, reasoning } = await analyseSlop(id , title, description)
  if (reasoning != 'failed to parse') await redis.set(`slop:${id}`, is_slop.toString(), 'EX', 60 * 60 * 24 * 7)

  return is_slop
}

export { parseSlop }